--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/5/2022 22:40:48
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS salon_manga;

CREATE DATABASE IF NOT EXISTS salon_manga
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE salon_manga;

--
-- Create table `mangas`
--
CREATE TABLE IF NOT EXISTS mangas (
  idManga int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) DEFAULT NULL,
  autor varchar(50) DEFAULT NULL,
  imagen varchar(255) DEFAULT NULL,
  descripcionCorta varchar(150) DEFAULT NULL,
  descripcionLarga varchar(300) DEFAULT NULL,
  estado varchar(30) DEFAULT NULL,
  PRIMARY KEY (idManga)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table mangas
--
INSERT INTO mangas VALUES
(1, 'DanDanDan', 'Yukinobu Tatsu', '1.jpg', NULL, NULL, 'Emision'),
(2, 'Sono Bisque Doll Wa Koi wo Suru', 'Shin''ichi Fukuda', '2.jpg', NULL, NULL, 'Emision');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;