--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31/5/2022 23:08:59
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE salon_manga;

--
-- Drop table `mangas`
--
DROP TABLE IF EXISTS mangas;

--
-- Set default database
--
USE salon_manga;

--
-- Create table `mangas`
--
CREATE TABLE mangas (
  idManga int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(50) DEFAULT NULL,
  autor varchar(50) DEFAULT NULL,
  imagen varchar(255) DEFAULT NULL,
  descripcionCorta varchar(150) DEFAULT 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.',
  descripcionLarga varchar(300) DEFAULT NULL,
  estado varchar(30) DEFAULT NULL,
  PRIMARY KEY (idManga)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table mangas
--
INSERT INTO mangas VALUES
(1, 'DanDanDan', 'Yukinobu Tatsu', '1.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(2, 'Sono Bisque Doll Wa Koi wo Suru', 'Shin''ichi Fukuda', '2.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(3, 'Shingeki No Kyojin', 'Hajime Isayama', '3.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Finalizado'),
(4, 'Kakko no Iinazuke', 'Miki Yoshikawa', '4.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(5, 'Kawaii dake ja Nai Shikimori-san', 'Keigo Maki', '5.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(6, 'Kaguya-sama: Love Is War', 'Aka Akasaka', '6.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(7, 'Jujutsu Kaisen', 'Gege Akutami', '7.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(8, 'Komi-san wa, Komyushō Desu', 'Tomohito Oda', '8.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(9, 'Mieruko-chan', 'Tomoki Izumi', '9.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Emision'),
(10, 'Dr. Stone', 'Riichiro Inagaki', '10.jpg', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Et nesciunt facilis excepturi adipisci voluptatum, corporis error nisi unde.', NULL, 'Finalizado');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;